server:
  port: 8080
  tomcat:
    threads:
      max: 5000
      min-spare: 200
    accept-count: 10000
    max-connections: 10000
    # 连接超时时间60秒
    connection-timeout: 600000
  servlet:
    context-path: /czyjy